[package]
name = "linux-controller-mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
gilrs = "0.11.*"
enigo = "0.6.*"
iced = "0.13.*"
uuid = "1.19.*"
serde = { version = "1.0.*", features = ["derive"] }
